Repository SpinalHDL/SpinalHDL, pull requests merged in 2022-10, with the labels that each got.

#898 add toBytes to get fixed bytes from BigInt.
  core/src/main/scala/spinal/core/core.scala
  core/src/main/scala/spinal/core/sim/package.scala
  lib/src/main/scala/spinal/lib/Misc.scala
Labels: :sparkles: feature, :memo: doc needed

#900 Add SystemRDL RegIf exporter
  lib/src/main/scala/spinal/lib/bus/regif/Document/SystemRdlGenerator.scala
  tester/src/main/scala/spinal/tester/code/RegIfExample.scala
Labels: :sparkles: feature

#906 Allow braces
  core/src/main/scala/spinal/core/Data.scala
Labels: :art: api

#901 add createSelector to Mux and Demux IO.
  lib/src/main/scala/spinal/lib/Stream.scala
  tester/src/test/scala/spinal/tester/scalatest/FormalDeMuxTester.scala
  tester/src/test/scala/spinal/tester/scalatest/FormalMuxTester.scala
Labels: :sparkles: feature

#889 Lib: Add PackedBundle
  lib/src/main/scala/spinal/lib/PackedBundle.scala
  tester/src/test/scala/spinal/tester/scalatest/SpinalSimPackedBundleTester.scala
Labels: :sparkles: feature, :speech_balloon: need agreement

#821 feat(lib): add Axi4Unburster
  lib/src/main/scala/spinal/lib/bus/amba4/axi/Axi4Unburster.scala
  lib/src/main/scala/spinal/lib/bus/amba4/axi/sim/Agent.scala
  tester/src/test/scala/spinal/tester/scalatest/Axi4AdapterTester.scala
  tester/src/test/scala/spinal/tester/scalatest/Axi4SharedOnChipRamTester.scala
  tester/src/test/scala/spinal/tester/scalatest/Axi4SimAgentTester.scala
  tester/src/test/scala/spinal/tester/scalatest/Axi4UnburstTester.scala
Labels: :speech_balloon: need agreement

#914 build: fix simple warnings
  build.sbt
  core/src/main/scala/spinal/core/Bits.scala
  core/src/main/scala/spinal/core/MultiData.scala
  core/src/main/scala/spinal/core/SInt.scala
  core/src/main/scala/spinal/core/Struct.scala
  core/src/main/scala/spinal/core/Trait.scala
  core/src/main/scala/spinal/core/UInt.scala
  core/src/main/scala/spinal/core/internals/Expression.scala
  lib/src/main/scala/spinal/lib/bus/regif/BusIfAdapter/Axi4BusInterface.scala
  lib/src/main/scala/spinal/lib/bus/regif/BusIfAdapter/WishboneBusInterface.scala
  lib/src/main/scala/spinal/lib/bus/regif/BusInterface.scala
  lib/src/main/scala/spinal/lib/com/usb/sim/HostAgent.scala
  lib/src/main/scala/spinal/lib/generator/Generator.scala
  sim/src/main/scala/spinal/sim/VerilatorBackend.scala
  tester/src/main/scala/spinal/tester/code/Debug.scala
  tester/src/main/scala/spinal/tester/code/RegIfExample.scala
  tester/src/main/scala/spinal/tester/code/Trash.scala
  tester/src/test/scala/spinal/tester/external/External.scala
  tester/src/test/scala/spinal/tester/scalatest/I2CTester.scala
  tester/src/test/scala/spinal/tester/scalatest/RiscvTester.scala
  tester/src/test/scala/spinal/tester/scalatest/SpinalSimMiscTester.scala
Labels: :speech_balloon: need agreement

#908 Hide ci
  travis.sh
Labels: :globe_with_meridians: meta
